name: Ruby String Calculater CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - name: Install dependencies
        run: |
          gem install minitest
      - name: Run tests
        run: ruby test_string_calculator.rb